// Code generated by generate/extensions.go DO NOT EDIT.
package iterator

import "iterator/extended"

func (i Iterator[T]) SortedByInt(keyFunc func(T) int) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, false)}
}

func (i Iterator[T]) SortedByInt8(keyFunc func(T) int8) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, false)}
}

func (i Iterator[T]) SortedByInt16(keyFunc func(T) int16) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, false)}
}

func (i Iterator[T]) SortedByInt32(keyFunc func(T) int32) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, false)}
}

func (i Iterator[T]) SortedByInt64(keyFunc func(T) int64) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, false)}
}

func (i Iterator[T]) SortedByUint(keyFunc func(T) uint) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, false)}
}

func (i Iterator[T]) SortedByUint8(keyFunc func(T) uint8) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, false)}
}

func (i Iterator[T]) SortedByUint16(keyFunc func(T) uint16) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, false)}
}

func (i Iterator[T]) SortedByUint32(keyFunc func(T) uint32) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, false)}
}

func (i Iterator[T]) SortedByUint64(keyFunc func(T) uint64) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, false)}
}

func (i Iterator[T]) SortedByFloat32(keyFunc func(T) float32) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, false)}
}

func (i Iterator[T]) SortedByFloat64(keyFunc func(T) float64) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, false)}
}

func (i Iterator[T]) SortedByString(keyFunc func(T) string) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, false)}
}

func (i Iterator[T]) SortedByIntDescending(keyFunc func(T) int) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, true)}
}

func (i Iterator[T]) SortedByInt8Descending(keyFunc func(T) int8) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, true)}
}

func (i Iterator[T]) SortedByInt16Descending(keyFunc func(T) int16) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, true)}
}

func (i Iterator[T]) SortedByInt32Descending(keyFunc func(T) int32) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, true)}
}

func (i Iterator[T]) SortedByInt64Descending(keyFunc func(T) int64) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, true)}
}

func (i Iterator[T]) SortedByUintDescending(keyFunc func(T) uint) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, true)}
}

func (i Iterator[T]) SortedByUint8Descending(keyFunc func(T) uint8) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, true)}
}

func (i Iterator[T]) SortedByUint16Descending(keyFunc func(T) uint16) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, true)}
}

func (i Iterator[T]) SortedByUint32Descending(keyFunc func(T) uint32) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, true)}
}

func (i Iterator[T]) SortedByUint64Descending(keyFunc func(T) uint64) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, true)}
}

func (i Iterator[T]) SortedByFloat32Descending(keyFunc func(T) float32) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, true)}
}

func (i Iterator[T]) SortedByFloat64Descending(keyFunc func(T) float64) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, true)}
}

func (i Iterator[T]) SortedByStringDescending(keyFunc func(T) string) Iterator[T] {
	return Iterator[T]{iter: extended.SortingIterator(i.iter, keyFunc, true)}
}

func (i Iterator[T]) DistinctByInt(keyFunc func(T) int) Iterator[T] {
	return Iterator[T]{iter: extended.DistinctingIterator(i.iter, keyFunc)}
}

func (i Iterator[T]) DistinctByInt8(keyFunc func(T) int8) Iterator[T] {
	return Iterator[T]{iter: extended.DistinctingIterator(i.iter, keyFunc)}
}

func (i Iterator[T]) DistinctByInt16(keyFunc func(T) int16) Iterator[T] {
	return Iterator[T]{iter: extended.DistinctingIterator(i.iter, keyFunc)}
}

func (i Iterator[T]) DistinctByInt32(keyFunc func(T) int32) Iterator[T] {
	return Iterator[T]{iter: extended.DistinctingIterator(i.iter, keyFunc)}
}

func (i Iterator[T]) DistinctByInt64(keyFunc func(T) int64) Iterator[T] {
	return Iterator[T]{iter: extended.DistinctingIterator(i.iter, keyFunc)}
}

func (i Iterator[T]) DistinctByUint(keyFunc func(T) uint) Iterator[T] {
	return Iterator[T]{iter: extended.DistinctingIterator(i.iter, keyFunc)}
}

func (i Iterator[T]) DistinctByUint8(keyFunc func(T) uint8) Iterator[T] {
	return Iterator[T]{iter: extended.DistinctingIterator(i.iter, keyFunc)}
}

func (i Iterator[T]) DistinctByUint16(keyFunc func(T) uint16) Iterator[T] {
	return Iterator[T]{iter: extended.DistinctingIterator(i.iter, keyFunc)}
}

func (i Iterator[T]) DistinctByUint32(keyFunc func(T) uint32) Iterator[T] {
	return Iterator[T]{iter: extended.DistinctingIterator(i.iter, keyFunc)}
}

func (i Iterator[T]) DistinctByUint64(keyFunc func(T) uint64) Iterator[T] {
	return Iterator[T]{iter: extended.DistinctingIterator(i.iter, keyFunc)}
}

func (i Iterator[T]) DistinctByFloat32(keyFunc func(T) float32) Iterator[T] {
	return Iterator[T]{iter: extended.DistinctingIterator(i.iter, keyFunc)}
}

func (i Iterator[T]) DistinctByFloat64(keyFunc func(T) float64) Iterator[T] {
	return Iterator[T]{iter: extended.DistinctingIterator(i.iter, keyFunc)}
}

func (i Iterator[T]) DistinctByString(keyFunc func(T) string) Iterator[T] {
	return Iterator[T]{iter: extended.DistinctingIterator(i.iter, keyFunc)}
}
